sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t waritsan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true waritsan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'docker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-961178347814'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
